// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upjfjmpdcwiywzenomfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwamZqbXBkY3dpeXd6ZW5vbWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzI2OTcsImV4cCI6MjA2NjIwODY5N30.Xtu5rtvdoMMrzxa0GBIqxXAVIeusces4JV2MWnrDfu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);